// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkxcjcmxbrgwqhevzgqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpreGNqY214YnJnd3FoZXZ6Z3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NzY3ODksImV4cCI6MjA3ODU1Mjc4OX0.lSxtNaj5H7BKC0jSUKneWZK4Uc97UcL-knSA6eDHQDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});